[package]
name = "serr_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serr = { path = "../serr", features = ["derive"] }
thiserror = "2.0.12"
trybuild = "1.0.105"
